# Generated by Django 2.2.4 on 2019-08-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190816_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestproject',
            name='image',
            field=models.ImageField(upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='latestproject',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
