# Generated by Django 2.2.4 on 2019-08-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190816_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestproject',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
